
version: "3.9"
services:

  db:
    image: mariadb
    #image: mysql
    command: --bind-address=0.0.0.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro
      - ./_db_data:/var/lib/mysql

  blog:
    image: chialab/php:7.4-apache
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      DB_SERVER: ${DB_SERVER}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - .:/var/www/html

  admin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: ${DB_SERVER}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

