
version: "3.9"
services:

  db:
    image: mariadb
    #image: mysql
    command: --bind-address=0.0.0.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: verysecret
      MYSQL_DATABASE: blog_recetas
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: somepassword
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro
      - ./_db_data:/var/lib/mysql

  blog:
    image: chialab/php:7.4-apache
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      DB_SERVER: db
      DB_USER: dbuser
      DB_PASSWORD: somepassword
      DB_NAME: blog_recetas
    volumes:
      - .:/var/www/html

  admin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: somepassword

